# Generated by Django 5.2.1 on 2025-05-16 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='favorite_color',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='skin_tone',
        ),
    ]
