# Generated by Django 5.2.1 on 2025-05-19 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_date_of_birth_student_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='lastName',
            new_name='last_name',
        ),
    ]
