# Generated by Django 5.2.1 on 2025-05-20 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0006_remove_level_code'),
        ('students', '0005_rename_firstname_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='levels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='levels.level'),
            preserve_default=False,
        ),
    ]
