# Generated by Django 5.2.1 on 2025-05-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_levels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='levels',
            new_name='level',
        ),
    ]
