# Generated by Django 5.2.1 on 2025-05-28 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_rename_levels_student_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
