# Generated by Django 5.2.1 on 2025-05-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_rename_first_name_student_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='level',
        ),
    ]
