# Generated by Django 5.2.1 on 2025-06-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_remove_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('firstName', 'lastName', 'dob')},
        ),
    ]
