# Generated by Django 5.2.2 on 2025-06-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0002_alter_academicyear_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
