# Generated by Django 5.2.1 on 2025-06-18 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0003_alter_academicyear_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}/\\d{4}$', message='Name must be in the format "YYYY/YYYY" (e.g., "2024/2025")')]),
        ),
    ]
