# Generated by Django 5.2.1 on 2025-05-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='name',
        ),
        migrations.AddField(
            model_name='period',
            name='period',
            field=models.CharField(choices=[('1st', '1st Period'), ('2nd', '2nd Period'), ('3rd', '3rd Period'), ('1exam', 'First Semester Exam'), ('4th', '4th Period'), ('5th', '5th Period'), ('6th', '6th Period'), ('2exam', 'Second Semester Exam')], default='1st', max_length=10, unique=True),
        ),
    ]
