# Generated by Django 5.2.2 on 2025-06-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0002_remove_period_name_period_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='is_exam',
            field=models.BooleanField(default=False),
        ),
    ]
