# Generated by Django 5.2.2 on 2025-06-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0003_period_is_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.CharField(choices=[('1st', '1st period'), ('2nd', '2nd period'), ('3rd', '3rd period'), ('1exam', '1 semester exam'), ('4th ', '4th period'), ('5th ', '5th period'), ('6th ', '6th period'), ('2exam', '2 semester exam')], default='1st period', max_length=9, unique=True),
        ),
    ]
