# Generated by Django 5.2.1 on 2025-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periods', '0004_remove_period_created_at_alter_period_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.CharField(choices=[('1st', '1st period'), ('2nd', '2nd period'), ('3rd', '3rd period'), ('1exam', '1st semester exam'), ('4th', '4th period'), ('5th', '5th period'), ('6th', '6th period'), ('2exam', '2nd semester exam')], default='1st', max_length=9, unique=True),
        ),
    ]
