# Generated by Django 5.2.1 on 2025-05-21 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_sheets', '0001_initial'),
        ('levels', '0007_rename_levels_level_name'),
        ('periods', '0002_remove_period_name_period_period'),
        ('students', '0007_rename_levels_student_level'),
        ('subjects', '0002_subject_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradesheet',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level'),
        ),
        migrations.AlterField(
            model_name='gradesheet',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periods.period'),
        ),
        migrations.AlterField(
            model_name='gradesheet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='gradesheet',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
