# Generated by Django 5.2.1 on 2025-05-20 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade_sheets', '0001_initial'),
        ('grades', '0001_initial'),
        ('levels', '0006_remove_level_code'),
        ('periods', '0002_remove_period_name_period_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesheet',
            name='grades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.grade'),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level'),
        ),
        migrations.AddField(
            model_name='gradesheet',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periods.period'),
        ),
    ]
