# Generated by Django 5.2.1 on 2025-05-20 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_sheets', '0003_initial'),
        ('students', '0005_rename_firstname_student_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradesheet',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gradesheet', to='students.student'),
            preserve_default=False,
        ),
    ]
