# Generated by Django 5.2.1 on 2025-06-13 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_years', '0002_alter_academicyear_name'),
        ('grade_sheets', '0003_delete_gradesheet'),
        ('levels', '0010_alter_level_id_alter_level_name'),
        ('students', '0009_remove_student_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeSheetPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(max_length=512, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic_years.academicyear')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('level', 'student', 'academic_year')},
            },
        ),
    ]
