# Generated by Django 5.2.1 on 2025-06-18 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0004_alter_academicyear_name'),
        ('grade_sheets', '0004_initial'),
        ('levels', '0012_alter_level_options_level_created_at_and_more'),
        ('students', '0010_student_updated_at_alter_student_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelGradeSheetPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(max_length=255, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_years.academicyear')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
            ],
            options={
                'unique_together': {('level', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentGradeSheetPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_path', models.CharField(max_length=255, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_years.academicyear')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('student', 'level', 'academic_year')},
            },
        ),
        migrations.DeleteModel(
            name='GradeSheetPDF',
        ),
    ]
