# Generated by Django 5.2.1 on 2025-06-18 17:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade_sheets', '0005_levelgradesheetpdf_studentgradesheetpdf_and_more'),
        ('students', '0010_student_updated_at_alter_student_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelgradesheetpdf',
            name='student',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
            preserve_default=False,
        ),
    ]
