# Generated by Django 5.2.1 on 2025-05-20 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0002_remove_enrollment_date_enrolled'),
        ('periods', '0002_remove_period_name_period_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='enrollment.enrollment')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periods.period')),
            ],
        ),
    ]
