# Generated by Django 5.2.1 on 2025-05-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_remove_enrollment_period'),
        ('grades', '0004_alter_grade_subject'),
        ('periods', '0002_remove_period_name_period_period'),
        ('subjects', '0002_subject_created_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['enrollment', 'subject', 'period'], name='grades_grad_enrollm_281b84_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('enrollment', 'subject', 'period'), name='unique_grade'),
        ),
    ]
