# Generated by Django 5.2.1 on 2025-05-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0005_grade_grades_grad_enrollm_281b84_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(),
        ),
    ]
