# Generated by Django 5.2.1 on 2025-05-31 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0005_alter_enrollment_student_and_more'),
        ('grades', '0006_alter_grade_score'),
        ('periods', '0002_remove_period_name_period_period'),
        ('subjects', '0003_alter_subject_unique_together_alter_subject_level_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='unique_grade',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='grades_grad_enrollm_281b84_idx',
        ),
        migrations.AlterField(
            model_name='grade',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('enrollment', 'subject', 'period')},
        ),
    ]
