# Generated by Django 5.2.1 on 2025-06-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0007_remove_grade_unique_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
