# Generated by Django 5.2.2 on 2025-06-10 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_years', '0001_initial'),
        ('enrollment', '0008_alter_enrollment_academic_year'),
        ('levels', '0009_alter_level_options_alter_level_id_alter_level_name'),
        ('students', '0009_remove_student_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassFailedStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Failed'), ('CONDITIONAL', 'Pass Under Condition'), ('INCOMPLETE', 'Incomplete')], default='INCOMPLETE', max_length=12)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('validated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_years.academicyear')),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.enrollment')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_failed_statuses', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'level', 'academic_year')},
            },
        ),
    ]
