# Generated by Django 5.2.1 on 2025-05-20 10:30

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_remove_enrollment_date_enrolled'),
        ('periods', '0002_remove_period_name_period_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='periods.period'),
        ),
    ]
