# Generated by Django 5.2.1 on 2025-05-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_enrollment_date_enrolled_enrollment_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='period',
        ),
    ]
