# Generated by Django 5.2.1 on 2025-05-30 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_remove_enrollment_period'),
        ('levels', '0007_rename_levels_level_name'),
        ('students', '0008_rename_first_name_student_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'level')},
        ),
    ]
