# Generated by Django 5.2.1 on 2025-06-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_alter_enrollment_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.CharField(max_length=9),
        ),
    ]
