# Generated by Django 5.2.1 on 2025-06-02 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0001_initial'),
        ('enrollment', '0007_alter_enrollment_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_years.academicyear'),
        ),
    ]
