# Generated by Django 5.2.2 on 2025-06-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0001_initial'),
        ('enrollment', '0008_alter_enrollment_academic_year'),
        ('students', '0009_remove_student_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('pass', 'Pass'), ('failed', 'Failed'), ('conditional', 'Pass Under Condition'), ('none', 'None')], default='none', max_length=12),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_years.academicyear'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
