# Generated by Django 5.2.2 on 2025-06-11 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0009_enrollment_status_alter_enrollment_academic_year_and_more'),
        ('students', '0009_remove_student_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='students.student'),
        ),
    ]
