# Generated by Django 5.2.1 on 2025-06-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0010_alter_enrollment_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='status',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('ENROLLED', 'Enrolled'), ('WITHDRAWN', 'Withdrawn')], default='ENROLLED', max_length=10),
        ),
    ]
