# Generated by Django 5.2.1 on 2025-06-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_years', '0004_alter_academicyear_name'),
        ('enrollment', '0011_remove_enrollment_status_and_more'),
        ('levels', '0012_alter_level_options_level_created_at_and_more'),
        ('students', '0010_student_updated_at_alter_student_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'level', 'academic_year')},
        ),
    ]
