# Generated by Django 5.2.1 on 2025-05-20 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('levels', '0006_remove_level_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Math', 'Mathematics'), ('Eng', 'English'), ('Sci', 'Science'), ('Hist', 'History'), ('Geo', 'Geography'), ('Civ', 'Civics'), ('RME', 'RME'), ('Vob', 'Vobucabulary'), ('Lit', 'Literature'), ('Agr', 'Agriculture')], max_length=12)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='levels.level')),
            ],
        ),
    ]
