# Generated by Django 5.2.1 on 2025-05-31 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0007_rename_levels_level_name'),
        ('subjects', '0002_subject_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('level', 'subject')},
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.level'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
    ]
