# Generated by Django 5.2.1 on 2025-05-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_unique_together_alter_subject_level_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
    ]
