# Generated by Django 5.2.2 on 2025-06-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0009_alter_level_options_alter_level_id_alter_level_name'),
        ('subjects', '0004_alter_subject_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject', 'level']},
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('English', 'English'), ('Science', 'Science'), ('Civics', 'Civics'), ('History', 'History'), ('Geography', 'Geography'), ('RME', 'RME'), ('Vocabulary', 'Vocabulary'), ('Agriculture', 'Agriculture')], max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('subject', 'level')},
        ),
    ]
