# Generated by Django 5.2.2 on 2025-06-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_subject_options_alter_subject_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
