# Generated by Django 5.2.1 on 2025-06-18 08:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0012_alter_level_options_level_created_at_and_more'),
        ('subjects', '0006_alter_subject_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={},
        ),
        migrations.AddField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='levels.level'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z\\s]*(?<!\\s)$', message='Subject name must start with a capital letter and contain only letters and spaces, no trailing spaces.')]),
        ),
    ]
