# Generated by Django 5.2.1 on 2025-05-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='name',
            new_name='code',
        ),
        migrations.AddField(
            model_name='level',
            name='levels',
            field=models.CharField(choices=[('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
