# Generated by Django 5.2.1 on 2025-05-19 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_rename_name_level_code_level_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='levels',
            field=models.CharField(choices=[('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9')], max_length=3),
        ),
    ]
