# Generated by Django 5.2.1 on 2025-05-20 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0005_alter_level_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='code',
        ),
    ]
