# Generated by Django 5.2.1 on 2025-05-20 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0006_remove_level_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='levels',
            new_name='name',
        ),
    ]
