# Generated by Django 5.2.2 on 2025-06-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0008_alter_level_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.IntegerField(choices=[('7', '7'), ('8', '8'), ('9', '9')], editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9')], max_length=1, unique=True),
        ),
    ]
