# Generated by Django 5.2.2 on 2025-06-10 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0009_alter_level_options_alter_level_id_alter_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9')], default='7', max_length=1, unique=True),
        ),
    ]
