# Generated by Django 5.2.2 on 2025-06-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0010_alter_level_id_alter_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=13),
        ),
    ]
